msg='welcome to Python 101: Ikode'
  
print(msg)
print(msg+msg)
print(msg*2)
print(msg,msg)
print(msg.upper())
print(msg.lower())
print(msg.capitalize())
print(msg.title())
print(msg.count('Python'))
print(msg.count('o'))
print(len(msg))
print(msg[2])
print(msg[2:5])
print(msg[0:12])
print(msg[0:12:2])
print(msg[0:12:3])
print(msg[0:12:4])
print(msg[0:12:5])
print(msg[0:12:6])